version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "security-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-165uo40l9lng9"
s3_prefix = "security-aws"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
